FROM node:10.15.3

WORKDIR /src
COPY . .

RUN npm install
RUN npm run build

EXPOSE 80
CMD npm run start

# RUN npm install -g http-server
# RUN npm run generate
# EXPOSE 80
# CMD npm run generate && http-server dist
